---
title: "Statistical Research Skills - Assignment 3"
author: "Yile Shi"
date: "2022/4/16"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
# install.packages("gss")
# install.packages("kdensity")
# install.packages("ash")
library(tidyverse)
library(gss)
library(kdensity)
library(ash)
library(ggplot2)
```

## Overview

## Data Generating Processes and Preliminary Experiments

\begin{itemize}
  \item Kernel Density Estimation - KSE
  \item Average Shifted Histogram - ASH
  \item Penalized Likelihood Estimation - PLE
\end{itemize}

```{r echo = FALSE}
# set random seed
set.seed(1)

# data generating for one-shot experiments
data_1 <- rnorm(n = 1000, mean = 5, sd = 3)              # Normal(5, 3^2)
data_2 <- rbeta(n = 1000, shape1 = 1, shape2 = 10)       # Beta(1, 10)
```

```{r include = FALSE}
# data_1 ~ Normal(5, 9)
# Average Shifted Histogram
ash_1 <- ash1(bin1(data_1, ab = c(range(data_1)[1], 
                                  range(data_1)[2]), nbin = 50))

# Penalized Likelihood Estimation
ple_1 <- ssden(~ data_1, domain = data.frame(data_1 = c(range(data_1)[1],
                                                        range(data_1)[2])))
```

```{r echo = FALSE}
# visualize the accurate density and estimations
x_1 <- seq(range(data_1)[1], range(data_1)[2], length = 1000)
# histogram
hist(data_1, freq = FALSE, main = "Density plot of Normal(5, 9)", 
     xlab = "x", ylim = c(0, 0.15))
# accurate density
lines(x_1, dnorm(x_1, mean = 5, sd = 3), lwd = 2, col = "orange")
# Kernel Density Estimates
lines(density(data_1, from = range(data_1)[1], to = range(data_1)[2]), 
      lwd = 2, col = "red")
rug(jitter(data_1), side = 1, col = "red")
# Average Shifted Estimates
lines(ash_1, lwd = 2, col = "green")
# Penalized Likelihood Estimates
lines(x_1, dssden(ple_1, x_1), lwd = 2, col = "blue")
# legend
legend("topright", legend = c("Accurate density", "Kernel density estimation",
                              "Average shifted histogram", 
                              "Penalized density estimation"),
       lwd = c(2, 2, 2, 2), col = c("orange", "red", "green", "blue"), 
       bty = "n")
```

## Monte Carlo Simulation Study

```{r, include = FALSE}
# data_1 ~ Normal(5, 9)

# function to compute ISE for both density estimation methods
ise_norm <- function(n){
  # This function is defined to get the Integrated Squared Error for both 
  # Kernel Density Estimation and Penalized Likelihood Estimation 
  # based on data from Normal(5, 9) distribution
  
  # simulated data from Normal(5, 9)
  x <- rnorm(n, mean = 5, sd = 3)
  
  # Kernel Density Estimation
  # compute the kernel density estimates
  kde <- kdensity(x, bw = "nrd0", kernel = "gaussian", 
                  support = c(min(x), max(x)))
  # compute the corresponding squared errors
  se_kde <- function(x) (kde(x) - dnorm(x, 5, 3))^2
  # compute the integrated se
  ise_kde <- integrate(se_kde, lower = min(x), upper = max(x))$value
  
  # Average Shifted Histogram
  ash <- ash1(bin1(x, ab = c(min(x), max(x)), nbin = 50))
  se_ash <- splinefun(ash$x, (ash$y - dnorm(ash$x, 5, 3))^2)
  ise_ash <- integrate(se_ash, lower = min(x), upper = max(x))$value
  
  # Penalized Likelihood Estimation
  # compute the penalized likelihood estimates
  ple <- ssden(~x, domain = data.frame(x = c(min(x), max(x))))
  # compute the corresponding squared errors
  se_ple <- function(x) (dssden(ple, x) - dnorm(x, 5, 3))^2
  # compute the integrated se
  ise_ple <- integrate(se_ple, lower = min(x), upper = max(x))$value
  
  return(c(ise_kde, ise_ash, ise_ple))
  
}

set.seed(1)
# sample size = 250
ise_250 <- matrix(0, nrow = 100, ncol = 3)
for (i in 1:100){
  ise_250[i, 1] <- ise_norm(250)[1]
  ise_250[i, 2] <- ise_norm(250)[2]
  ise_250[i, 3] <- ise_norm(250)[3]
}

# sample size = 500
ise_500 <- matrix(0, nrow = 100, ncol = 3)
for (i in 1:100){
  ise_500[i, 1] <- ise_norm(500)[1]
  ise_500[i, 2] <- ise_norm(500)[2]
  ise_500[i, 3] <- ise_norm(500)[3]
}

# sample size = 1000
ise_1000 <- matrix(0, nrow = 100, ncol = 3)
for (i in 1:100){
  ise_1000[i, 1] <- ise_norm(1000)[1]
  ise_1000[i, 2] <- ise_norm(1000)[2]
  ise_1000[i, 3] <- ise_norm(1000)[3]
}
```

```{r, echo = FALSE}
# box-plots for ISE based on different methods
par(mfrow = c(1, 3))
boxplot(ise_250 ~ col(ise_250), names = c("KDE", "ASH", "PLE"), 
        col = c("gray", "green", "lightblue"), main = "sample size = 250",
        xlab = "estimator", ylab = "ise")
boxplot(ise_500 ~ col(ise_500), names = c("KDE", "ASH", "PLE"), 
        col = c("gray", "green", "lightblue"), main = "sample size = 500",
        xlab = "estimator", ylab = "ise")
boxplot(ise_1000 ~ col(ise_1000), names = c("KDE", "ASH", "PLE"), 
        col = c("gray", "green", "lightblue"), main = "sample size = 1000",
        xlab = "estimator", ylab = "ise")

# line graphs for mean ISE with CIs
# mean ISE for each method 
ise_250_mean <- apply(ise_250, 2, mean)
ise_500_mean <- apply(ise_500, 2, mean)
ise_1000_mean <- apply(ise_1000, 2, mean)

# standard deviations for ISEs
ise_250_sd <- apply(ise_250, 2, sd)
ise_500_sd <- apply(ise_500, 2, sd)
ise_1000_sd <- apply(ise_1000, 2, sd)

# data frame for critical values of ISEs
rep_ise <- data.frame(size = c(250, 500, 1000), 
                      mean_kse = c(ise_250_mean[1], ise_500_mean[1],
                                   ise_1000_mean[1]),
                      CI_kse_lower = c(ise_250_mean[1] - 1.96*ise_250_sd[1],
                                       ise_500_mean[1] - 1.96*ise_500_sd[1],
                                       ise_1000_mean[1] - 1.96*ise_1000_sd[1]),
                      CI_kse_upper = c(ise_250_mean[1] + 1.96*ise_250_sd[1],
                                       ise_500_mean[1] + 1.96*ise_500_sd[1],
                                       ise_1000_mean[1] + 1.96*ise_1000_sd[1]),
                      mean_ash = c(ise_250_mean[2], ise_500_mean[2],
                                   ise_1000_mean[2]),
                      CI_ash_lower = c(ise_250_mean[2] - 1.96*ise_250_sd[2],
                                       ise_500_mean[2] - 1.96*ise_500_sd[2],
                                       ise_1000_mean[2] - 1.96*ise_1000_sd[2]),
                      CI_ash_upper = c(ise_250_mean[2] + 1.96*ise_250_sd[2],
                                       ise_500_mean[2] + 1.96*ise_500_sd[2],
                                       ise_1000_mean[2] + 1.96*ise_1000_sd[2]),
                      mean_ple = c(ise_250_mean[3], ise_500_mean[3],
                                   ise_1000_mean[3]),
                      CI_ple_lower = c(ise_250_mean[3] - 1.96*ise_250_sd[3],
                                       ise_500_mean[3] - 1.96*ise_500_sd[3],
                                       ise_1000_mean[3] - 1.96*ise_1000_sd[3]),
                      CI_ple_upper = c(ise_250_mean[3] + 1.96*ise_250_sd[3],
                                       ise_500_mean[3] + 1.96*ise_500_sd[3],
                                       ise_1000_mean[3] + 1.96*ise_1000_sd[3]))

# make the plot
plot <- ggplot(rep_ise, aes(x = size)) +
  geom_point(aes(y = mean_kse, color = "mean ISE for KSE"), size = 1.25) + 
  geom_line(aes(y = mean_kse)) + 
  geom_ribbon(aes(ymin = CI_kse_lower, ymax = CI_kse_upper, 
                  fill = "95% CI for KSE"), alpha = 0.3) + 
  geom_point(aes(y = mean_ash, color = "mean ISE for ASH"), size = 1.25) + 
  geom_line(aes(y = mean_ash)) + 
  geom_ribbon(aes(ymin = CI_ash_lower, ymax = CI_ash_upper, 
                  fill = "95% CI for ASH"), alpha = 0.3) + 
  geom_point(aes(y = mean_ple, color = "mean ISE for PLE"), size = 1.25) + 
  geom_line(aes(y = mean_ple)) + 
  geom_ribbon(aes(ymin = CI_ple_lower, ymax = CI_ple_upper, 
                  fill = "95% CI for PLE"), alpha = 0.3) + 
  ggtitle("Critical values for mean ISE of different methods") + 
  theme(plot.title = element_text(hjust = 0.5)) + 
  labs(x = "sample size", y = "ISE", color = "", fill = "") 

plot
```
```{r}

```

